name: Tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 2 * * 1-5"
jobs:
  cgl:
    name: CGL
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --config development-configuration/php-fixer-config.php --dry-run --using-cache=no

  unit_tests:
    name: Unit Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2' ]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Unit
        run: vendor/bin/phpunit tests/

  PHPStan:
    name: PHPStan PHP 8.2
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-progress

      - name: PHPStan
        run: vendor/bin/phpstan analyse -l max -c development-configuration/phpstan.neon src tests
